UpStore/urls.py
from django.contrib import admin
from django.urls import path,include
# import for static and media images
from django.conf import settings
from django.conf.urls.static import static, serve

handler404 = 'main.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    # include main wint namespace
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    # path('seller/', include(('seller.urls', 'seller'), namespace='seller')),
    # path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    # path('ratings/', include(('ratings.urls', 'ratings'), namespace='ratings')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login', views.login_view, name='login'),   ## accounts/login (accounts come from main urls.py)
    path('register', views.register, name='register'),  ## accounts/register
    path('logout', views.logout_view, name='logout'),        ## accounts/logout
    # path('dashboard', views.dashboard, name='dashboard'),   ## accounts/dashboard
    # path('agents/<str:pk>/', views.agents, name='agents'),   ## accounts/agents
    # path('verify-email/', views.verifyEmail, name='verify_email'),
    # path('verify-otp/', views.verifyOTP, name='verify_otp'),
    # path('forget-password/', views.forgetPassword, name='forget_password'),
    # path('reset-password/', views.resetPassword, name='reset_password'),
]

main/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

]

store/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'product', views.ProductViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customers/', views.customers, name='customers'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/', views.cart, name='cart'),
    path('product-details/<int:id>', views.productDetails, name='product-details'),
    path('add-to-cart/', views.addToCart, name='add-to-cart'),
    path('remove-from-cart/<int:id>', views.removeFromCart, name='remove-from-cart'),
]
urlpatterns += router.urls

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Upstore - {% block title %}{% endblock %} </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>


<body class="bg-body-tertiary ">
    <nav class="navbar navbar-expand-lg bg-primary sticky-top" data-bs-theme="dark">
        <div class="container-fluid px-5">
            <a class="navbar-brand" href="{% url 'main:home' %}">Upstore</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse w-100 " id="navbarSupportedContent">
                <form action="#" class="col-lg-8 mx-3 ">
                    <div class="input-group">
                        <input type="text" class="form-control bg-white" placeholder="Search...">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-light" style="border-radius:0 !important;">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
                <ul class="navbar-nav col-lg-4">
                    <li class="nav-item me-2">
                        <a class="nav-link active" aria-current="page" href="#" data-bs-target="#home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"></a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"></li>
                        <a class="nav-link" href="{% url 'accounts:register' %}">Profile</a>
                    </li>
                    <li class="nav-item"></li>
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" style="position: relative;" href="{% url 'store:cart' %}">
                            <i class="fa fa-cart-shopping fs-4"></i>
                            <span class="cart-count">{{ cart_count }}</span>
                        </a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <div class="footer py-5 bg-body-secondary  ">
        <div class="container py-4">
            <div class="row">
                <div class="col-lg-3">
                    <h4 class="text-primary">Customer Care</h4>
                    <div class="fs-6">Help Center</div>
                    <div class="fs-6">How to Buy</div>
                    <div class="fs-6">Returns & Refunds</div>
                    <div class="fs-6">Contact Us</div>
                    <div class="fs-6">Terms & Conditions</div>
                    <div class="fs-6">CCMS - Central Complain Management System</div>

                    <h4 class="text-primary mt-4">Earn with Upstore</h4>
                    <div class="fs-6">Upstore University</div>
                    <div class="fs-6">Sell on Upstore</div>
                    <div class="fs-6">Code of Conduct</div>
                    <div class="fs-6">Join with Upstore Affiliate Program</div>
                </div>
                <div class="col-lg-3">
                    <h4 class="text-primary">Upstore</h4>
                    <div class="fs-6">About Upstore</div>
                    <div class="fs-6">Digital Payments</div>
                    <div class="fs-6">Upstore Card</div>
                    <div class="fs-6">Upstore Blog</div>
                    <div class="fs-6">Upstore Cares</div>
                    <div class="fs-6">Upstore Mart</div>
                    <div class="fs-6">Privicy Policy</div>
                    <div class="fs-6">Upstore App</div>
                    <div class="fs-6">Upstore Exclusives</div>
                    <div class="fs-6">Upstore Donate</div>
                </div>
                <div class="col-lg-3">
                    <h4 class="text-primary">Upstore International</h4>
                    <div class="fs-6">Help Center</div>
                    <div class="fs-6">How to Buy</div>
                    <div class="fs-6">Returns & Refunds</div>
                    <div class="fs-6">Contact Us</div>
                    <div class="fs-6">Terms & Conditions</div>
                    <div class="fs-6">CCMS - Central Complain Management System</div>
                </div>
                <div class="col-lg-3">
                    <h4 class="text-primary">Help Center</h4>
                    <div class="fs-6">Help Center</div>
                    <div class="fs-6">How to Buy</div>
                    <div class="fs-6">Returns & Refunds</div>
                    <div class="fs-6">Contact Us</div>
                    <div class="fs-6">Terms & Conditions</div>
                    <div class="fs-6">CCMS - Central Complain Management System</div>
                </div>

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
    </script>
    <script>
        $(document).ready(function () {
            // Truncate Product titles
            $('.truncate-text').each(function () {
                var maxLength = 23;
                var text = $(this).text();
                if (text.length > maxLength) {
                    $(this).text(text.substring(0, maxLength) + '...');
                }
            });
        });
    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <ul class="list-group col-lg-3 my-3">
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Women's and Children's Fashion</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Health & Beauty</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Watches, Bags, Jwelllery</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Men's and Boy's Fashion</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Mother and baby</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Electronics Device</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">TV & Home Appliances</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Electronic Accessories</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Groceries</span>
                    </li>
                    <li class="list-group-item sm-text text-secondary ">
                        <span><i class="fa fa-user mx-1"></i></span>
                        <span class="">Sprots & Outdoors</span>
                    </li>
                </ul>
                <div class="col-lg-9 my-3">
                    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="{% static 'gallery/7dd9370f-20f9-4cef-8778-f6eff550c136.jpg_1200x1200.jpg' %}" class="d-block w-100"
                                    alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'gallery/a35eb3b2-6a6a-4dca-978a-b2c41a6783ca.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'gallery/b337144d-f37f-4011-baa8-bfbb143446a8.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="container">
            <div class="row p-3 bg-body-white my-4">
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/best-price-tag.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Best Price Guaranteed</div>
                    <div class="border-right pr-3"></div>
                </div>
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/9f19fb02-e022-473a-873d-bb99306c9263.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Everyday Low Price</div>
                    <div class="border-right pr-3"></div>
                </div>
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/whole sale tag.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Whole Sale price</div>
                    <div class="border-right pr-3"></div>
                </div>
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/free-delivery-tag.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Free Delivery</div>
                    <div class="border-right pr-3"></div>
                </div>
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/mart-tag.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Mart</div>
                    <div class="border-right pr-3"></div>
                </div>
                <div class="col-lg-2 pr-3">
                    <img src="{% static 'gallery/fashion tag.png' %}" alt="" class="img-fluid ">
                    <div class="fs-6 text-center bold">Fashion</div>
                    <div class="border-right pr-3"></div>
                </div>
                
                
               

            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="container my-4">
            <h3>Just For You</h3>
            <div class="product-container">
                {% for product in products %}
                {% include 'components/product_card.html' %}
                {% endfor %}
            </div>
        </div>
    </div>

 {% endblock %}