UpStore/urls.py
from django.contrib import admin
from django.urls import path,include
# import for static and media images
from django.conf import settings
from django.conf.urls.static import static, serve

handler404 = 'main.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    # include main wint namespace
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    # path('seller/', include(('seller.urls', 'seller'), namespace='seller')),
    # path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    # path('ratings/', include(('ratings.urls', 'ratings'), namespace='ratings')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

]

store/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'product', views.ProductViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customers/', views.customers, name='customers'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/', views.cart, name='cart'),
    path('product-details/<int:id>', views.productDetails, name='product-details'),
    path('add-to-cart/', views.addToCart, name='add-to-cart'),
    path('remove-from-cart/<int:id>', views.removeFromCart, name='remove-from-cart'),
]
urlpatterns += router.urls

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField()
    stock = models.IntegerField(default=0)
    image_url = models.ImageField(upload_to='images/', null=True, blank=True)
    brand = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product'
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image_url = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, default=None, null=True, blank=True)
    name = models.CharField(max_length=255)
    quantity = models.IntegerField()

    def __unicode__(self):
        return self.name
    def subtotal(self):
        return self.product.price * self.quantity

store/views.py
from django.shortcuts import render, redirect
from store.models import *
from rest_framework import viewsets
from .serializer import ProductSerializer


# Create your views here.
def home(request):
    return render(request, 'store/home.html')

def products(request):
    return render(request, 'store/products.html')

def customers(request):
    return render(request, 'store/customers.html')

def cart(request):
    items = Cart.objects.filter(user=request.user)
    total = 0
    for item in items:
        total += item.quantity * item.product.price

    context = {
        'items': items,
        'total': total
    }
    return render(request, 'store/cart.html', context)

def checkout(request):
    return render(request, 'store/checkout.html')

def productDetails(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }

    return render(request, 'store/product-details.html', context)

def addToCart(request):
    if request.method == "POST":
        product_name = request.POST['product_name']
        quantity = request.POST['quantity']
        product = Product.objects.get(name=product_name)
        print(product)
        cart = Cart.objects.update_or_create(
            user=request.user,
            name=product.name,
            product = product,
            quantity=quantity
        )
       
        return redirect('store:cart')

def removeFromCart(request, id):
    product = Product.objects.get(id=id)

    Cart.objects.get(name=product.name).delete()
    return redirect('store:cart')

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

templates/store/cart.html
{% extends "base.html" %} {% load static %} {% block title %}My Shopping Cart{% endblock %} {% block content %}
<div class="container" style="margin-bottom: 200px;">
    <h2 class="m-4 ">My Shopping Cart</h2>
    <div class="row col-8 m-auto py-5 border my-5 ">
        <div class="col-12 px-3">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.product.price }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.subtotal }}</td>
                        <td>
                            <a href="{% url 'store:remove-from-cart' item.product.id %}">Remove</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="4"></td>
                        <td colspan="2">Total: {{ total }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-12">
            <a href="{% url 'store:checkout' %}" class="btn btn-warning w-100">Checkout</a>
        </div>
    </div>
</div>


{% endblock %}

templates/store/checkout.html
{% extends "base.html" %} 
{% load custom_tags %}
{% load static %} 
{% block title %}My Shopping Cart{% endblock %} 
{% block content %}

<div class="container" bis_skin_checked="1">
    <main>
        <div class="py-5 text-center" bis_skin_checked="1">
            <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72"
                height="57">
            <h2>Checkout form</h2>
            <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form
                group has a validation state that can be triggered by attempting to submit the form without completing
                it.</p>
        </div>

        <div class="row g-5" bis_skin_checked="1">
            <div class="col-md-5 col-lg-4 order-md-last" bis_skin_checked="1">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Your cart</span>
                    <span class="badge bg-primary rounded-pill">{{user.cart_set.count}}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for item in user.cart_set.all %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div bis_skin_checked="1">  
                            <h6 class="my-0">{{item.product}}  X{{item.quantity}}</h6>
                            
                            <small class="text-body-secondary">Brief description</small>
                        </div>
                        <span class="text-body-secondary">${{item.subtotal}}</span>
                    </li>
                    {% endfor %}

                    <li class="list-group-item d-flex justify-content-between bg-body-tertiary">
                        <div class="text-success" bis_skin_checked="1">
                            <h6 class="my-0">Promo code</h6>
                            <small>EXAMPLECODE</small>
                        </div>
                        <span class="text-success">−$5</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>${% get_total user.cart_set.all %}</strong>
                    </li>
                </ul>

                <form class="card p-2">
                    <div class="input-group" bis_skin_checked="1">
                        <input type="text" class="form-control" placeholder="Promo code">
                        <button type="submit" class="btn btn-secondary">Redeem</button>
                    </div>
                </form>
            </div>
            <div class="col-md-7 col-lg-8" bis_skin_checked="1">
                <h4 class="mb-3">Billing address</h4>
                <form class="needs-validation" novalidate="">
                    <div class="row g-3" bis_skin_checked="1">
                        <div class="col-sm-6" bis_skin_checked="1">
                            <label for="firstName" class="form-label">First name</label>
                            <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Valid first name is required.
                            </div>
                        </div>

                        <div class="col-sm-6" bis_skin_checked="1">
                            <label for="lastName" class="form-label">Last name</label>
                            <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Valid last name is required.
                            </div>
                        </div>

                        <div class="col-12" bis_skin_checked="1">
                            <label for="username" class="form-label">Username</label>
                            <div class="input-group has-validation" bis_skin_checked="1">
                                <span class="input-group-text">@</span>
                                <input type="text" class="form-control" id="username" placeholder="Username"
                                    required="">
                                <div class="invalid-feedback" bis_skin_checked="1">
                                    Your username is required.
                                </div>
                            </div>
                        </div>

                        <div class="col-12" bis_skin_checked="1">
                            <label for="email" class="form-label">Email <span
                                    class="text-body-secondary">(Optional)</span></label>
                            <input type="email" class="form-control" id="email" placeholder="you@example.com">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Please enter a valid email address for shipping updates.
                            </div>
                        </div>

                        <div class="col-12" bis_skin_checked="1">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Please enter your shipping address.
                            </div>
                        </div>

                        <div class="col-12" bis_skin_checked="1">
                            <label for="address2" class="form-label">Address 2 <span
                                    class="text-body-secondary">(Optional)</span></label>
                            <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                        </div>

                        <div class="col-md-5" bis_skin_checked="1">
                            <label for="country" class="form-label">Country</label>
                            <select class="form-select" id="country" required="">
                                <option value="">Choose...</option>
                                <option>United States</option>
                            </select>
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Please select a valid country.
                            </div>
                        </div>

                        <div class="col-md-4" bis_skin_checked="1">
                            <label for="state" class="form-label">State</label>
                            <select class="form-select" id="state" required="">
                                <option value="">Choose...</option>
                                <option>California</option>
                            </select>
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Please provide a valid state.
                            </div>
                        </div>

                        <div class="col-md-3" bis_skin_checked="1">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" placeholder="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Zip code required.
                            </div>
                        </div>
                    </div>

                    <hr class="my-4">

                    <div class="form-check" bis_skin_checked="1">
                        <input type="checkbox" class="form-check-input" id="same-address">
                        <label class="form-check-label" for="same-address">Shipping address is the same as my billing
                            address</label>
                    </div>

                    <div class="form-check" bis_skin_checked="1">
                        <input type="checkbox" class="form-check-input" id="save-info">
                        <label class="form-check-label" for="save-info">Save this information for next time</label>
                    </div>

                    <hr class="my-4">

                    <h4 class="mb-3">Payment</h4>

                    <div class="my-3" bis_skin_checked="1">
                        <div class="form-check" bis_skin_checked="1">
                            <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked=""
                                required="">
                            <label class="form-check-label" for="credit">Credit card</label>
                        </div>
                        <div class="form-check" bis_skin_checked="1">
                            <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
                            <label class="form-check-label" for="debit">Debit card</label>
                        </div>
                        <div class="form-check" bis_skin_checked="1">
                            <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                            <label class="form-check-label" for="paypal">PayPal</label>
                        </div>
                    </div>

                    <div class="row gy-3" bis_skin_checked="1">
                        <div class="col-md-6" bis_skin_checked="1">
                            <label for="cc-name" class="form-label">Name on card</label>
                            <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                            <small class="text-body-secondary">Full name as displayed on card</small>
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Name on card is required
                            </div>
                        </div>

                        <div class="col-md-6" bis_skin_checked="1">
                            <label for="cc-number" class="form-label">Credit card number</label>
                            <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Credit card number is required
                            </div>
                        </div>

                        <div class="col-md-3" bis_skin_checked="1">
                            <label for="cc-expiration" class="form-label">Expiration</label>
                            <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Expiration date required
                            </div>
                        </div>

                        <div class="col-md-3" bis_skin_checked="1">
                            <label for="cc-cvv" class="form-label">CVV</label>
                            <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                            <div class="invalid-feedback" bis_skin_checked="1">
                                Security code required
                            </div>
                        </div>
                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                </form>
            </div>
        </div>
    </main>

    <footer class="my-5 pt-5 text-body-secondary text-center text-small">
        <p class="mb-1">© 2017–2024 Company Name</p>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#">Privacy</a></li>
            <li class="list-inline-item"><a href="#">Terms</a></li>
            <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
    </footer>
</div>
{% endblock %}

templates/store/product-details.html
{% extends "base.html" %} {% load static %} {% block title %}My Shopping Cart{% endblock %} {% block content %}

<div class="container mt-4 bg-white my-4">
    <nav aria-label="breadcrumb">
        
        <ol class="breadcrumb">
            <a href="{% url 'main:home' %}"><i class="fa fa-house my-1 mx-2"></i></a>
            <li class="breadcrumb-item"><a href="#">{{product.category}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{product.name}}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-lg-3">
            <img style="width: 100%;" src="{% if product.image_url %} {{product.image_url.url}} {% else %} {% static "gallery/demo.webp" %} {% endif %}" alt="">
        </div>
        <div class="col-lg-6">
            <h1>{{product.name}}</h1>
            <div class="review">
                <img src="{% static 'gallery/vecteezy_5-star-rating-review-star-png-transparent_9663927_155.png' %}"
                    width="80px" alt="">
                <span class="text-secondary ">(97)</span>Ratings
            </div>
            <hr>
            <div class="text-primary bold h2">
                $ {{product.price}}
            </div>
            <div class="wrap">
                <span class="text-secondary text-decoration-line-through ">$ 50</span>
                <span class="text-secondary ">-40%</span>
            </div>

            <div class="wrap">
                <div class="row">
                    <div class="col-4 h4">
                        Quantity
                    </div>
                    <div class="col">
                        <form>
                            <button class="ml-4 btn-minus" type="button"><i class="fa fa-minus"></i></button>

                            <input type="number" value="1" min="1" max="10" width="15px" style="text-align: center;" name="quantity">
                            <button class="btn-plus" type="button"><i class="fa fa-plus"></i></button>
                            <input type="hidden" name="product-name" value="{{product.name}}">
                        </form>
                    </div>
                </div>



            </div>
            <div class="row my-2">
                <div class="col">
                    <button class="btn btn-primary btn-buy-now">Buy Now</button>
                    

                </div>
                <div class="col">
                    <button class="btn btn-warning btn-add-to-cart">Add to Cart</button>
                </div>
            </div>

        </div>
        

        <div class="col-lg-3 bg-secondary-light">
            <h5>Delivery</h5>
            <div class="row">
                <div class="col-1">
                    <i class="fa fa-location-dot"></i>
                </div>
                <div class="col-8">
                    Dhaka, Dhaka North, Banani Road No. 12 - 19
                </div>
                <div class="col-2"><a href="">Change</a></div>
            </div><hr>
            <div class="row">
                <div class="col-1">
                    <i class="fa fa-truck"></i>
                </div>
                <div class="col-7">
                    Standard Delivery: 
                </div>
                <div class="col-3">৳ 50</div>
            </div><hr>
            <div class="row">
                <div class="col-1">
                    <i class="fa fa-calendar"></i>
                </div>
                <div class="col-8">
                    Delivery by 12th Aug
                </div>
        
            </div><hr>
            <div class="row">
                <div class="col-1">
                    <i class="fa fa-credit-card"></i>
                </div>
                <div class="col-8">
                    Cash on Delivery Available
                </div>
 
            </div><hr>

        </div>
    </div>
    
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>


    $(document).ready(function(){
        $('.btn-plus').click(function(){
            var value = parseInt($('input[type="number"]').val());
            if(value < 10){
                value = value + 1;
                $('input[type="number"]').val(value);
            }
        })
        $('.btn-minus').click(function(){
            var value = parseInt($('input[type="number"]').val());
            if(value > 1){
                value = value - 1;
                $('input[type="number"]').val(value);
            }
        })
        // use ajax to add to cart
        $('.btn-add-to-cart').click(function(e){
            e.preventDefault();
            var quantity = $('input[name="quantity"]').val();
            var product_name = $('input[name="product-name"]').val();
            $.ajax({
                url: "{% url 'store:add-to-cart' %}",
                type: 'POST',
                data: {
                    'quantity': quantity,
                    'product_name': product_name,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success: function(response){
                    console.log(response);
                    $('.cart-count').text(response.cart_count);
                }
            })
        })
    })
        
</script>

{% endblock %}