UpStore/urls.py
from django.contrib import admin
from django.urls import path,include
# import for static and media images
from django.conf import settings
from django.conf.urls.static import static, serve

handler404 = 'main.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    # include main wint namespace
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    # path('seller/', include(('seller.urls', 'seller'), namespace='seller')),
    # path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    # path('ratings/', include(('ratings.urls', 'ratings'), namespace='ratings')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

]

store/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'product', views.ProductViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customers/', views.customers, name='customers'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/', views.cart, name='cart'),
    path('product-details/<int:id>', views.productDetails, name='product-details'),
    path('add-to-cart/', views.addToCart, name='add-to-cart'),
    path('remove-from-cart/<int:id>', views.removeFromCart, name='remove-from-cart'),
]
urlpatterns += router.urls

templates/components/product_card.html
{% load static %}
<a href="{% url 'store:product-details' product.id %}">
    <div class="card   ">
        <div class="aspect-ratio-16x9">
            <img src="{% if product.image_url %} {{product.image_url.url}} {% else %} {% static "gallery/demo.webp" %} {% endif %}" class="card-img-top img-fluid card-img" alt="...">
        </div>

        
        <div class="card-body">
            <h5 class="fs-5 product-title truncate-text">{{product.name}}</h5>
            <div class="text-primary bold">
                $ {{product.price}}
            </div>
            <div class="wrap">
                <span class="text-secondary text-decoration-line-through ">$ 50</span>
                <span class="text-secondary ">-40%</span>
            </div>
            <div class="review">
                <img src="{% static 'gallery/vecteezy_5-star-rating-review-star-png-transparent_9663927_155.png' %}" width="80px"
                    alt="">
                <span class="text-secondary ">(97)</span>
            </div>
        </div>
    </div>
</a>